import XCTest
@testable import VNPlayerCore

/// Round-trips against archives written by Python's `zipfile`.
///
/// The fixtures are generated by `Tests/generate_fixtures.py` and committed. That an
/// independent implementation produced them is the point: if our reader and our writer
/// shared a misunderstanding of the format, a self-generated fixture would confirm the
/// misunderstanding rather than catch it.
final class ArchiveImporterTests: XCTestCase {

    private var staging: URL!

    override func setUpWithError() throws {
        staging = FileManager.default.temporaryDirectory
            .appendingPathComponent("vnplayer-tests-\(UUID().uuidString)", isDirectory: true)
        try FileManager.default.createDirectory(at: staging, withIntermediateDirectories: true)
    }

    override func tearDownWithError() throws {
        try? FileManager.default.removeItem(at: staging)
    }

    private func fixture(_ name: String) throws -> URL {
        let url = Bundle.module.url(forResource: "Fixtures/\(name)", withExtension: nil)
            ?? Bundle.module.bundleURL
                .appendingPathComponent("Fixtures")
                .appendingPathComponent(name)

        guard FileManager.default.fileExists(atPath: url.path) else {
            throw XCTSkip("fixture \(name) not found at \(url.path)")
        }
        return url
    }

    private func contents(_ relativePath: String) -> Data? {
        try? Data(contentsOf: staging.appendingPathComponent(relativePath))
    }

    private func extractedPaths() -> Set<String> {
        guard let enumerator = FileManager.default.enumerator(
            at: staging, includingPropertiesForKeys: [.isRegularFileKey]) else { return [] }

        var result = Set<String>()
        let prefix = staging.standardizedFileURL.path + "/"

        for case let url as URL in enumerator {
            var isDirectory: ObjCBool = false
            FileManager.default.fileExists(atPath: url.path, isDirectory: &isDirectory)
            guard !isDirectory.boolValue else { continue }
            let path = url.standardizedFileURL.path
            if path.hasPrefix(prefix) {
                result.insert(String(path.dropFirst(prefix.count)))
            }
        }
        return result
    }

    private func assertThrows(
        _ expected: ImportError,
        _ body: () throws -> Void,
        file: StaticString = #filePath,
        line: UInt = #line
    ) {
        do {
            try body()
            XCTFail("expected \(expected), but nothing was thrown", file: file, line: line)
        } catch let error as ImportError {
            XCTAssertEqual(error, expected, file: file, line: line)
        } catch {
            XCTFail("expected \(expected), got \(error)", file: file, line: line)
        }
    }

    // MARK: - The happy path

    func testDeflatedArchiveRoundTrips() throws {
        let importer = ArchiveImporter()
        let url = try fixture("good-deflated.zip")

        let plan = try importer.plan(archiveURL: url, archiveFileName: "good-deflated.zip")
        XCTAssertEqual(plan.identity.title, "MyGame")
        XCTAssertEqual(plan.identity.id, "mygame")
        XCTAssertEqual(plan.distributionRoot, "MyGame-1.2.3-pc")

        try importer.extract(archiveURL: url, plan: plan, to: staging)

        XCTAssertEqual(extractedPaths(), [
            "game/script.rpy",
            "game/script.rpyc",
            "game/options.rpy",
            "game/gui/window_icon.png",
        ])

        // Byte-for-byte, not merely present. A reader that mangles content while
        // producing the right filenames is the exact failure a round-trip must catch.
        XCTAssertEqual(contents("game/script.rpy"),
                       Data("label start:\n    \"Hello.\"\n    return\n".utf8))
        XCTAssertEqual(contents("game/options.rpy"),
                       Data("define config.name = \"Fixture\"\n".utf8))
    }

    func testStoredArchiveRoundTrips() throws {
        // Method 0. Deflate is the common case, but a stored entry takes a different
        // path through the reader and has its own way to go wrong.
        let importer = ArchiveImporter()
        let url = try fixture("good-stored.zip")
        let plan = try importer.plan(archiveURL: url, archiveFileName: "good-stored.zip")
        try importer.extract(archiveURL: url, plan: plan, to: staging)

        XCTAssertEqual(contents("game/script.rpy"),
                       Data("label start:\n    \"Hello.\"\n    return\n".utf8))
    }

    func testGameAtArchiveRootUsesTheFileName() throws {
        let importer = ArchiveImporter()
        let url = try fixture("game-at-root.zip")
        let plan = try importer.plan(archiveURL: url, archiveFileName: "Rooted Game-1.0-pc.zip")

        XCTAssertEqual(plan.distributionRoot, "")
        XCTAssertEqual(plan.identity.title, "Rooted Game")

        try importer.extract(archiveURL: url, plan: plan, to: staging)
        XCTAssertTrue(extractedPaths().contains("game/script.rpy"))
    }

    func testWrapperDirectoryNamedGameIsNotMistakenForTheGameDirectory() throws {
        // "Game/game/..." -- a wrapper folder whose name case-folds onto the real game
        // directory. A case-insensitive shallowest match roots this at "", extracts one
        // level too deep, and produces a game Ren'Py cannot load. The fixture below has
        // exactly this shape, which is how the bug was found.
        let importer = ArchiveImporter()
        let url = try fixture("utf8-names.zip")
        let plan = try importer.plan(archiveURL: url, archiveFileName: "utf8-names.zip")

        XCTAssertEqual(plan.distributionRoot, "Game")
        XCTAssertEqual(plan.identity.title, "Game")
    }

    func testUTF8NamesSurvive() throws {
        let importer = ArchiveImporter()
        let url = try fixture("utf8-names.zip")
        let plan = try importer.plan(archiveURL: url, archiveFileName: "utf8-names.zip")
        try importer.extract(archiveURL: url, plan: plan, to: staging)

        let paths = extractedPaths()
        XCTAssertTrue(paths.contains("game/audio/効果音.ogg"), "got \(paths)")
        XCTAssertTrue(paths.contains("game/images/café.png"), "got \(paths)")
    }

    func testZip64EntryFieldsAreParsed() throws {
        // ZIP64 extra fields on each entry, but Python still writes a CLASSIC 22-byte
        // trailer for this archive -- so usedZip64Trailer is correctly false here. The
        // first version of this test asserted true and failed, because it was written
        // against a field name (`isZip64`) that promised more than the field measured.
        let importer = ArchiveImporter()
        let url = try fixture("zip64.zip")

        let summary = try ZipDirectoryReader.read(contentsOf: url)
        XCTAssertFalse(summary.usedZip64Trailer)
        XCTAssertEqual(summary.declaredEntryCount, 4)

        let plan = try importer.plan(archiveURL: url, archiveFileName: "zip64.zip")
        try importer.extract(archiveURL: url, plan: plan, to: staging)
        XCTAssertTrue(extractedPaths().contains("game/script.rpy"))
    }

    func testZip64TrailerIsParsed() throws {
        // The ZIP64 end-of-central-directory path. Nothing exercised it until this
        // fixture existed: the classic trailer only saturates past 65535 entries or
        // 4 GB, so the reader's ZIP64 branch was shipped untested. The fixture
        // synthesises a real ZIP64 trailer over a small archive -- see the generator.
        let url = try fixture("zip64-trailer.zip")

        let summary = try ZipDirectoryReader.read(contentsOf: url)
        XCTAssertTrue(summary.usedZip64Trailer)
        // Read out of the ZIP64 record, since the classic one says 0xFFFF.
        XCTAssertEqual(summary.declaredEntryCount, 4)
        XCTAssertFalse(summary.isMultiDisk)

        // And it still extracts: a fixture that exercised the parser but could not be
        // read would not tell us the parse produced usable values.
        let importer = ArchiveImporter()
        let plan = try importer.plan(archiveURL: url, archiveFileName: "zip64-trailer.zip")
        try importer.extract(archiveURL: url, plan: plan, to: staging)
        XCTAssertTrue(extractedPaths().contains("game/script.rpy"))
    }

    // MARK: - Structure rejections

    func testArchiveWithoutGameDirectoryIsRejected() throws {
        let url = try fixture("no-game-dir.zip")
        assertThrows(.notARenpyGame) {
            _ = try ArchiveImporter().plan(archiveURL: url, archiveFileName: "no-game-dir.zip")
        }
    }

    func testEmptyArchiveIsRejected() throws {
        let url = try fixture("empty.zip")
        assertThrows(.notARenpyGame) {
            _ = try ArchiveImporter().plan(archiveURL: url, archiveFileName: "empty.zip")
        }
    }

    func testNonZipIsRejected() throws {
        let url = try fixture("not-a-zip.bin")
        assertThrows(.notAZipArchive) {
            _ = try ArchiveImporter().plan(archiveURL: url, archiveFileName: "not-a-zip.bin")
        }
    }

    func testMultiDiskIsRejected() throws {
        let url = try fixture("multi-disk.zip")
        assertThrows(.multiDiskArchive) {
            _ = try ArchiveImporter().plan(archiveURL: url, archiveFileName: "multi-disk.zip")
        }
    }

    // MARK: - Path attacks. Each asserts the SPECIFIC error, not merely that it failed.

    func testTraversalIsRejected() throws {
        let url = try fixture("traversal.zip")
        assertThrows(.unsafePath(entry: "Game/../../../etc/passwd")) {
            _ = try ArchiveImporter().plan(archiveURL: url, archiveFileName: "traversal.zip")
        }
    }

    func testAbsolutePathIsRejected() throws {
        let url = try fixture("absolute-path.zip")
        assertThrows(.unsafePath(entry: "/etc/passwd")) {
            _ = try ArchiveImporter().plan(archiveURL: url, archiveFileName: "absolute-path.zip")
        }
    }

    func testDrivePathIsRejected() throws {
        let url = try fixture("drive-path.zip")
        assertThrows(.unsafePath(entry: "C:/Windows/evil.dll")) {
            _ = try ArchiveImporter().plan(archiveURL: url, archiveFileName: "drive-path.zip")
        }
    }

    func testAttackArchivesWriteNothing() throws {
        // Rejection has to happen in plan(), before extraction touches the filesystem.
        // A design that extracted first and validated after would leave the hostile file
        // on disk even though the import "failed".
        for name in ["traversal.zip", "absolute-path.zip", "drive-path.zip"] {
            let url = try fixture(name)
            _ = try? ArchiveImporter().plan(archiveURL: url, archiveFileName: name)
            XCTAssertEqual(extractedPaths(), [], "\(name) wrote something")
        }
    }

    func testCaseInsensitiveDuplicateIsRejected() throws {
        // iOS folds case, so these two entries are one destination. Letting the second
        // silently overwrite the first is how a crafted archive replaces a vetted file.
        let url = try fixture("duplicate-case.zip")
        assertThrows(.duplicateEntry(path: "Game/game/SCRIPT.rpy")) {
            _ = try ArchiveImporter().plan(archiveURL: url, archiveFileName: "duplicate-case.zip")
        }
    }

    // MARK: - Damage

    func testTruncatedArchiveIsRejected() throws {
        let url = try fixture("truncated.zip")
        // A half-file has no end-of-central-directory record left, so it is
        // indistinguishable from "not a zip" at the trailer level. Either message is
        // honest; assert that it is one of them rather than pretending to more precision
        // than the format allows.
        do {
            _ = try ArchiveImporter().plan(archiveURL: url, archiveFileName: "truncated.zip")
            XCTFail("truncated archive was accepted")
        } catch let error as ImportError {
            XCTAssertTrue(
                error == .notAZipArchive || error == .truncatedArchive
                    || error == .cannotOpenArchive,
                "unexpected \(error)")
        }
    }

    func testChecksumMismatchIsCaught() throws {
        // The check that makes a bad download fail at import rather than as a corrupt
        // asset hours into a playthrough.
        let importer = ArchiveImporter()
        let url = try fixture("crc-corrupt.zip")
        let plan = try importer.plan(archiveURL: url, archiveFileName: "crc-corrupt.zip")

        do {
            try importer.extract(archiveURL: url, plan: plan, to: staging)
            XCTFail("corrupt payload was accepted")
        } catch let error as ImportError {
            guard case .checksumMismatch = error else {
                return XCTFail("expected checksumMismatch, got \(error)")
            }
        }
    }

    // MARK: - Engine detection

    func testRenpy7IsRefusedFromLibDirectory() throws {
        let url = try fixture("renpy7-lib.zip")
        assertThrows(.needsRenpy7) {
            _ = try ArchiveImporter().plan(archiveURL: url, archiveFileName: "renpy7-lib.zip")
        }
    }

    func testRenpy7IsRefusedFromVCVersion() throws {
        let url = try fixture("renpy7-vcversion.zip")
        assertThrows(.needsRenpy7) {
            _ = try ArchiveImporter().plan(archiveURL: url, archiveFileName: "renpy7-vcversion.zip")
        }
    }

    func testRenpy8IsDetected() throws {
        for name in ["renpy8-lib.zip", "renpy8-vcversion.zip"] {
            let url = try fixture(name)
            let plan = try ArchiveImporter().plan(archiveURL: url, archiveFileName: name)
            XCTAssertEqual(plan.engine, .renpy8, name)
        }
    }

    func testGameOnlyArchiveIsUnknownAndStillImports() throws {
        // A game/-only archive carries no engine marker. Refusing everything we cannot
        // classify would reject a large share of perfectly good Ren'Py 8 games, so
        // unknown must import.
        let url = try fixture("good-deflated.zip")
        let plan = try ArchiveImporter().plan(archiveURL: url, archiveFileName: "good-deflated.zip")
        XCTAssertEqual(plan.engine, .unknown)
    }

    // MARK: - Pruning

    func testPruningRemovesDesktopFilesAndKeepsGameLib() throws {
        let importer = ArchiveImporter(pruneDesktopFiles: true)
        let url = try fixture("desktop-cruft.zip")
        let plan = try importer.plan(archiveURL: url, archiveFileName: "desktop-cruft.zip")

        XCTAssertGreaterThan(plan.prunedBytes, 0)

        try importer.extract(archiveURL: url, plan: plan, to: staging)
        let paths = extractedPaths()

        XCTAssertFalse(paths.contains("MyGame.exe"))
        XCTAssertFalse(paths.contains("MyGame.sh"))
        XCTAssertFalse(paths.contains("lib/py3-windows-x86_64/python.dll"))
        XCTAssertFalse(paths.contains("renpy/__init__.py"))

        // The one that matters: a real game file inside a directory called lib.
        XCTAssertTrue(paths.contains("game/lib/helper.rpy"), "game/lib was pruned; got \(paths)")
        XCTAssertTrue(paths.contains("game/script.rpy"))
    }

    func testPruningOffKeepsEverything() throws {
        let importer = ArchiveImporter(pruneDesktopFiles: false)
        let url = try fixture("desktop-cruft.zip")
        let plan = try importer.plan(archiveURL: url, archiveFileName: "desktop-cruft.zip")

        XCTAssertEqual(plan.prunedBytes, 0)

        try importer.extract(archiveURL: url, plan: plan, to: staging)
        let paths = extractedPaths()
        XCTAssertTrue(paths.contains("MyGame.exe"))
        XCTAssertTrue(paths.contains("lib/py3-windows-x86_64/python.dll"))
    }

    // MARK: - Caps

    func testEntryCountCapIsEnforced() throws {
        let importer = ArchiveImporter(caps: ImportCaps(
            maxEntries: 2,
            maxTotalUncompressed: .max,
            maxEntryUncompressed: .max,
            maxCompressionRatio: .infinity
        ))
        let url = try fixture("good-deflated.zip")

        do {
            _ = try importer.plan(archiveURL: url, archiveFileName: "good-deflated.zip")
            XCTFail("cap was not enforced")
        } catch let error as ImportError {
            guard case .tooManyEntries = error else {
                return XCTFail("expected tooManyEntries, got \(error)")
            }
        }
    }

    func testTotalSizeCapIsEnforced() throws {
        let importer = ArchiveImporter(caps: ImportCaps(
            maxEntries: .max,
            maxTotalUncompressed: 10,
            maxEntryUncompressed: .max,
            maxCompressionRatio: .infinity
        ))
        let url = try fixture("good-deflated.zip")

        do {
            _ = try importer.plan(archiveURL: url, archiveFileName: "good-deflated.zip")
            XCTFail("cap was not enforced")
        } catch let error as ImportError {
            guard case .archiveTooLarge = error else {
                return XCTFail("expected archiveTooLarge, got \(error)")
            }
        }
    }

    func testCancellationStopsExtractionAndThrows() throws {
        let importer = ArchiveImporter()
        let url = try fixture("good-deflated.zip")
        let plan = try importer.plan(archiveURL: url, archiveFileName: "good-deflated.zip")

        assertThrows(.cancelled) {
            try importer.extract(
                archiveURL: url, plan: plan, to: self.staging, isCancelled: { true })
        }
        XCTAssertEqual(extractedPaths(), [], "cancelled import left files behind")
    }
}
